sudo: false
language: node_js
node_js:
- '0.12'
before_install:
- npm install -g grunt-cli
- npm install -g jspm
- jspm config registries.github.auth $JSPM_GITHUB_AUTH_TOKEN
before_script:
- grunt 'file-creator:youTubeAPIKey'
- grunt 'less'
- jspm install
install: npm install
env:
  global:
  - secure: N/yV6FNB4bOhqk5AgGTMylbHTk/2uZK/kfOmIiDRhK6eIeuDcyb/KyasAeFztnzRxbjeLx1pCimSafthLbL4VxP1MtNag/qYwg/58tQ89guuvkFuAdYAVk28Ub6giW6mAQZyfzehrwOOVZeMhl7w4Kg9UNC3Y4iGF746pkworGM=